In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [19]:
x1 = [10,15,20,25]
x2 = [5,10,15,20]

y = [17,27,37,47]

In [20]:
x1 = np.array(x1)
x2 = np.array(x2)

y = np.array(y)

In [21]:
df = pd.DataFrame()
df["X1"] = x1
df["X2"] = x2
df["y"] = y

df


X1  X2   y
0  10   5  17
1  15  10  27
2  20  15  37
3  25  20  47

In [28]:
lm = LinearRegression()
lm.fit(x1.reshape(-1,1), y.reshape(-1,1))

LinearRegression()

In [29]:
lm.coef_

array([[2.]])

In [30]:
lm.intercept_

array([-3.])

In [31]:
lm = LinearRegression()
lm.fit(df[["X1", "X2"]], y.reshape(-1,1))

LinearRegression()

In [32]:
lm.coef_

array([[1., 1.]])

In [33]:
lm.intercept_

array([2.])

In [42]:
import pandas as pd 

name = ['Reetesh', 'Shruti', 'Kaustubh', 'Vikas', 'Mahima', 'Akshay']
response = ['No', 'Maybe', 'Yes', 'Yes', 'Maybe', 'Yes']

df = pd.DataFrame({'Name': name,'Response': response})
df

Name Response
0   Reetesh       No
1    Shruti    Maybe
2  Kaustubh      Yes
3     Vikas      Yes
4    Mahima    Maybe
5    Akshay      Yes

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      6 non-null      object
 1   Response  6 non-null      object
dtypes: object(2)
memory usage: 224.0+ bytes


In [44]:
def response_map(x):
    return x.map({'Yes': 1, 'No': 0, 'Maybe': 0.5})

df['Response'] = df[['Response']].apply(response_map)

In [45]:
df['Response']

0    0.0
1    0.5
2    1.0
3    1.0
4    0.5
5    1.0
Name: Response, dtype: float64

In [46]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [47]:
min = MinMaxScaler()
ss = StandardScaler()

In [49]:
min.fit_transform(df[["Response"]])

array([[0. ],
       [0.5],
       [1. ],
       [1. ],
       [0.5],
       [1. ]])

In [50]:
ss.fit_transform(df[["Response"]])

array([[-1.78885438],
       [-0.4472136 ],
       [ 0.89442719],
       [ 0.89442719],
       [-0.4472136 ],
       [ 0.89442719]])

In [59]:
df["Random"] = [1,1,1,1,1,1]

min = MinMaxScaler()
min.fit_transform(df[["Random"]])

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])